version: "3.9"
services:
  keycloak: 
    container_name: iam_sbm 
    image: "jboss/keycloak:15.0.2" 
    depends_on: 
      - "postgres" 
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports: 
      - "127.0.0.1:8180:8080" 
      - "127.0.0.1:8787:8787" # debug port 
    networks: 
      - iam-local